### ISSUE TITLE
TypeError when pane has no 'pane_current_path' key

### ISSUE THREAD

**Issue by amonsch** [tony/tmuxp#103]
``` python
Traceback (most recent call last):
  File "/usr/local/bin/tmuxp", line 9, in <module>
    load_entry_point('tmuxp==0.1.12', 'console_scripts', 'tmuxp')()
  File "/usr/local/lib/python2.7/dist-packages/tmuxp/cli.py", line 975, in main
    command_freeze(args)
  File "/usr/local/lib/python2.7/dist-packages/tmuxp/cli.py", line 351, in command_freeze
    sconf = freeze(session)
  File "/usr/local/lib/python2.7/dist-packages/tmuxp/workspacebuilder.py", line 308, in freeze
    'cd ' + p.get('pane_current_path')
TypeError: coercing to Unicode: need string or buffer, NoneType found
```

I have somehow managed to not have a current path for a pane in my tmux session.

**Comment by tony** [comment]
@amonsch Do you still get this error?

I'm interested to know what path you were in when you tried to freeze your session. I'd like to be able to recreate this.
