### ISSUE TITLE
Inconsistent use of tab and spaces

### ISSUE THREAD

**Issue by alem0lars** [tony/tmuxp#117]
When building the documentation `make -C doc html` python hangs because `aafig.py` contains mixed spaces and tabs.

This is the error I get:

```
# Sphinx version: 1.3.1
# Python version: 3.3.5 (CPython)
# Docutils version: 0.12 release
# Jinja2 version: 2.8
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "/home/alem0lars/downloads/tmuxp-0.9.0/.env/lib/python3.3/site-packages/sphinx/cmdline.py", line 244, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/home/alem0lars/downloads/tmuxp-0.9.0/.env/lib/python3.3/site-packages/sphinx/application.py", line 143, in __init__
    self.setup_extension(extension)
  File "/home/alem0lars/downloads/tmuxp-0.9.0/.env/lib/python3.3/site-packages/sphinx/application.py", line 429, in setup_extension
    mod = __import__(extension, None, None, ['setup'])
  File "/home/alem0lars/downloads/tmuxp-0.9.0/doc/_ext/aafig.py", line 95
    image_node.aafig = dict(options = aafig_options, text = text)
                                                                ^
TabError: inconsistent use of tabs and spaces in indentation
```

BTW I've checked the file and it contains multiple of these mistakes.

**Comment by tony** [comment]
@alem0lars Nice catch. We should be linting this.

Do you want to do a PR for this?  It could be for indentation, or adding a script to PEP8 the code.

**Comment by fpietka** [comment]
It seems this issue has been fixed already

**Comment by tony** [comment]
In master, yes, we had a huge cleanup.  We have ``make flake8`` and ``make watch_flake8`` too

closing this issue.

**Comment by Nic30** [comment]
Today it happend me again, 
pip3 install sphinxcontrib-aafig
Python 3.5.2

Exception occurred:
  File "/usr/local/lib/python3.5/dist-packages/sphinx/application.py", line 512, in setup_extension
    mod = __import__(extension, None, None, ['setup'])
  File "/usr/local/lib/python3.5/dist-packages/sphinxcontrib/aafig.py", line 95
    image_node.aafig = dict(options = aafig_options, text = text)
                                                                ^
TabError: inconsistent use of tabs and spaces in indentation

pip3 show sphinxcontrib-aafig
---
Metadata-Version: 1.1
Name: sphinxcontrib-aafig
Version: 1.0
Summary: aafig Sphinx extension
Home-page: http://packages.python.org/sphinxcontrib-aafig/
Author: Leandro Lucarella
Author-email: llucax@gmail.com


Package is old(2009-11-16) please update it.
