### ISSUE TITLE
tmuxp crashs on first start with Tmux 2.1

### ISSUE THREAD

**Issue by byaruhaf** [tony/tmuxp#125]
Hello 
i have problem tmuxp on start with tmux 2.1

```
λ VIDIA ~ → pdb
(I) [04:10:33] tmuxp.cli cli.load_workspace():270 Loading /home/byaruhaf/.tmuxp/pdb.yaml.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tmuxp/cli.py", line 271, in load_workspace
    builder.build()
  File "/usr/local/lib/python2.7/dist-packages/tmuxp/workspacebuilder.py", line 114, in build
    'session_name': self.sconf['session_name']
  File "/usr/local/lib/python2.7/dist-packages/tmuxp/util.py", line 191, in findWhere
    return self.where(attrs)[0]
  File "/usr/local/lib/python2.7/dist-packages/tmuxp/util.py", line 222, in where
    return list(filter(by, self.children))
  File "/usr/local/lib/python2.7/dist-packages/tmuxp/server.py", line 166, in sessions
    return self.list_sessions()
  File "/usr/local/lib/python2.7/dist-packages/tmuxp/server.py", line 160, in list_sessions
    Session(server=self, **s) for s in self._sessions
  File "/usr/local/lib/python2.7/dist-packages/tmuxp/server.py", line 151, in _sessions
    return self._list_sessions()
  File "/usr/local/lib/python2.7/dist-packages/tmuxp/server.py", line 124, in _list_sessions
    raise exc.TmuxpException(proc.stderr)
TmuxpException: [u'error connecting to /tmp/tmux-1000/default (No such file or directory)']
```

when i start tmux with the tmux command directtly 
then start tmuxp all works okay.

**Comment by byaruhaf** [comment]
Error fixed after upgrade of tmuxp, closing issue.
