### ISSUE TITLE
macos sierra, can't load sessions

### ISSUE THREAD

**Issue by oschrenk** [tony/tmuxp#173]
```
brew info tmux | head -1
tmux: stable 2.2, HEAD
tmuxp --version
tmuxp 1.1.0

tmuxp load -y personal
Traceback (most recent call last):
  File "/usr/local/bin/tmuxp", line 11, in <module>
    sys.exit(cli.cli())
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/tmuxp/cli.py", line 481, in command_load
    load_workspace(config[-1], **tmux_options)
  File "/usr/local/lib/python2.7/site-packages/tmuxp/cli.py", line 247, in load_workspace
    if builder.session_exists(session_name):
  File "/usr/local/lib/python2.7/site-packages/tmuxp/workspacebuilder.py", line 104, in session_exists
    'session_name': session_name
  File "/usr/local/lib/python2.7/site-packages/libtmux/common.py", line 266, in find_where
    return self.where(attrs)[0]
  File "/usr/local/lib/python2.7/site-packages/libtmux/common.py", line 292, in where
    return list(filter(by, self.children))
  File "/usr/local/lib/python2.7/site-packages/libtmux/server.py", line 164, in sessions
    return self.list_sessions()
  File "/usr/local/lib/python2.7/site-packages/libtmux/server.py", line 158, in list_sessions
    Session(server=self, **s) for s in self._sessions
  File "/usr/local/lib/python2.7/site-packages/libtmux/server.py", line 149, in _sessions
    return self._list_sessions()
  File "/usr/local/lib/python2.7/site-packages/libtmux/server.py", line 127, in _list_sessions
    raise exc.LibTmuxException(proc.stderr)
libtmux.exc.LibTmuxException: [u'[warn] kq_init: detected broken kqueue; not using.: File exists', u'no server running on /private/tmp/tmux-502/default']
```

This is actually an underlying [tmux 2.2 issue](https://github.com/tmux/tmux/issues/475) but it might be good to have people know that at the moment tmuxp is not behaving as expected on macOS 10.12.

**Comment by oschrenk** [comment]
Crossposting this from [here](https://github.com/tmux/tmux/issues/475)

```
export EVENT_NOKQUEUE=1
```

worked for me

**Comment by thiagodebastos** [comment]
@oschrenk Hey there, I'm very new to tmux and landed here looking for a fix to this very issue. Where did you add that export? Just in `tmux.conf`?

**Comment by oschrenk** [comment]
No. You have to set in your terminal If you use bash, which I presume yu can do that in your .bash_profile file.

See also here: http://stackoverflow.com/questions/14524590/how-to-add-export-statement-in-a-bash-profile-file <http://stackoverflow.com/questions/14524590/how-to-add-export-statement-in-a-bash-profile-file>
