### ISSUE TITLE
Session name with number at end won't load

### ISSUE THREAD

**Issue by borisjoffe** [tony/tmuxp#183]
tmux 2.3
tmuxp 1.2.2

Repro steps:
- Freeze a current tmux session
- Change `session_name` to `test` in the yaml file
- Duplicate the yaml file
- Change `session_name` to `test2` in the duplicate file
- Use tmuxp to load `test2` in a terminal window
- Use tmuxp to load `test` in a different window

Expected result:
- Both sessions load

Actual result:
- Second session shows message "test is already running. Attach?"
- If you try to attach to the session, it crashes with the following stacktrace:

```
Traceback (most recent call last):
  File "/bin/tmuxp", line 11, in <module>
    load_entry_point('tmuxp==1.2.2', 'console_scripts', 'tmuxp')()
  File "/usr/lib/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.5/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.5/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3.5/site-packages/tmuxp/cli.py", line 511, in command_load
    load_workspace(config[-1], **tmux_options)
  File "/usr/lib/python3.5/site-packages/tmuxp/cli.py", line 253, in load_workspace
    reattach(builder.session)
  File "/usr/lib/python3.5/site-packages/tmuxp/cli.py", line 244, in reattach
    session.attach_session()
AttributeError: 'NoneType' object has no attribute 'attach_session'
```

<br>
#132 was a similar issue except with dots instead of numbers

Also, if the number is within the `session_name`, it works correctly, and if `test` is loaded before `test2`, it also works correctly.

**Comment by BlitzKraft** [comment]
I have a similar issue, when the window title is empty. 
```
Traceback (most recent call last):
  File "/usr/local/bin/tmuxp", line 11, in <module>
    load_entry_point('tmuxp==1.2.2', 'console_scripts', 'tmuxp')()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tmuxp/cli.py", line 511, in command_load
    load_workspace(config[-1], **tmux_options)
  File "/usr/local/lib/python2.7/dist-packages/tmuxp/cli.py", line 221, in load_workspace
    sconfig = config.expand(sconfig, os.path.dirname(config_file))
  File "/usr/local/lib/python2.7/dist-packages/tmuxp/config.py", line 265, in expand
    expand(window, parent=sconf) for window in sconf['windows']
  File "/usr/local/lib/python2.7/dist-packages/tmuxp/config.py", line 193, in expand
    sconf['window_name'] = expandshell(sconf['window_name'])
  File "/usr/local/lib/python2.7/dist-packages/tmuxp/config.py", line 117, in expandshell
    return os.path.expandvars(os.path.expanduser(_path))
  File "/usr/lib/python2.7/posixpath.py", line 261, in expanduser
    if not path.startswith('~'):
AttributeError: 'NoneType' object has no attribute 'startswith'
```

**Comment by BlitzKraft** [comment]
I found a work-around by running `tmux rename-window ''` in one of the panes in the specified window. That works for me. Not as elegant, but achieves what I want.
