### ISSUE TITLE
start_directory not working as expected

### ISSUE THREAD

**Issue by IngoHeimbach** [tony/tmuxp#209]
I started using tmuxp recently (and it's great!) but I have some problems using `start_directory`. Assume, I would like to work on a project `~/project` with sub directories `src` and `test` and would like that tmuxp creates one window with two panes, one for each subdirectory. I tried to use the following yaml file for that:
```yaml
start_directory: ~/project
windows:
- window_name: dev
  focus: true
  panes:
  - focus: true
    start_directory: ./src
  - start_directory: ./test
```
When calling tmuxp I get the following exception:
```
Traceback (most recent call last):
  File "/usr/local/bin/tmuxp", line 11, in <module>
    sys.exit(cli.cli())
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tmuxp/cli.py", line 511, in command_load
    load_workspace(config[-1], **tmux_options)
  File "/usr/local/lib/python2.7/dist-packages/tmuxp/cli.py", line 221, in load_workspace
    sconfig = config.expand(sconfig, os.path.dirname(config_file))
  File "/usr/local/lib/python2.7/dist-packages/tmuxp/config.py", line 265, in expand
    expand(window, parent=sconf) for window in sconf['windows']
  File "/usr/local/lib/python2.7/dist-packages/tmuxp/config.py", line 303, in expand
    expand(pane, parent=sconf) for pane in sconf['panes']
  File "/usr/local/lib/python2.7/dist-packages/tmuxp/config.py", line 231, in expand
    cwd = parent['start_directory']
KeyError: u'start_directory'
```
To circumvent the problem I added a `start_directory` for the window as well:
```yaml
start_directory: ~/project
windows:
- window_name: dev
  focus: true
  start_directory: ./
  panes:
  - focus: true
    start_directory: ./src
  - start_directory: ./test
```
After that, the session can be created but the bash in the first pane uses `~/project` as current working directory instead of `~/project/src`. However, the second pane is fine.

The problem can be solved by setting the start directory of the window to `./src`, removing the `start_window` attribute from the first pane and setting the start directory of the second pane to `../test`.

**Comment by mikl** [comment]
I just hit this same problem with tmuxp 1.3.5. 

To work around this, `start_directory` must be set explicitly on all windows, not just inherited from the root.

<details>
 <summary>My traceback is similar</summary>
<pre><code>
Traceback (most recent call last):
  File "/usr/local/bin/tmuxp", line 11, in <module>
    sys.exit(cli.cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/tmuxp/cli.py", line 602, in command_load
    load_workspace(config[-1], **tmux_options)
  File "/usr/local/lib/python3.6/site-packages/tmuxp/cli.py", line 289, in load_workspace
    sconfig = config.expand(sconfig, os.path.dirname(config_file))
  File "/usr/local/lib/python3.6/site-packages/tmuxp/config.py", line 265, in expand
    expand(window, parent=sconf) for window in sconf['windows']
  File "/usr/local/lib/python3.6/site-packages/tmuxp/config.py", line 265, in <listcomp>
    expand(window, parent=sconf) for window in sconf['windows']
  File "/usr/local/lib/python3.6/site-packages/tmuxp/config.py", line 303, in expand
    expand(pane, parent=sconf) for pane in sconf['panes']
  File "/usr/local/lib/python3.6/site-packages/tmuxp/config.py", line 303, in <listcomp>
    expand(pane, parent=sconf) for pane in sconf['panes']
  File "/usr/local/lib/python3.6/site-packages/tmuxp/config.py", line 231, in expand
    cwd = parent['start_directory']
KeyError: 'start_directory'
</code></pre>
</details>

**Comment by samvv** [comment]
Can confirm this is an issue. I just had the same error.
