### ISSUE TITLE
Check if Tmux is installed

### ISSUE THREAD

**Issue by sdouche** [tony/tmuxp#229]
Hi,
Nasty error message if Tmux is not installed (version 1.2.7):

```tmuxp load ./mysession.yaml
Exception for None -V: 
[Errno 2] No such file or directory: 'None'
Traceback (most recent call last):
  File "/home/sdouche/.pyenv/versions/vdefault/bin/tmuxp", line 11, in <module>
    sys.exit(cli.cli())
  File "/home/sdouche/.pyenv/versions/3.6.0/envs/vdefault/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/sdouche/.pyenv/versions/3.6.0/envs/vdefault/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/sdouche/.pyenv/versions/3.6.0/envs/vdefault/lib/python3.6/site-packages/click/core.py", line 1063, in invoke
    Command.invoke(self, ctx)
  File "/home/sdouche/.pyenv/versions/3.6.0/envs/vdefault/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/sdouche/.pyenv/versions/3.6.0/envs/vdefault/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/sdouche/.pyenv/versions/3.6.0/envs/vdefault/lib/python3.6/site-packages/tmuxp/cli.py", line 318, in cli
    has_required_tmux_version()
  File "/home/sdouche/.pyenv/versions/3.6.0/envs/vdefault/lib/python3.6/site-packages/libtmux/common.py", line 414, in has_required_tmux_version
    proc = tmux_cmd('-V')
  File "/home/sdouche/.pyenv/versions/3.6.0/envs/vdefault/lib/python3.6/site-packages/libtmux/common.py", line 178, in __init__
    self.stdout = console_to_str(stdout)
```

**Comment by tony** [comment]
Would you like to make a PR / test? This should be an easy one.

**Comment by tony** [comment]
I may take this one on if you don't have time.

What we need:

1. libtmux to raise an exception that tmux wasn't found in paths. 
2. tmuxp should give a friendlier error message

**Comment by tony** [comment]
@sdouche This made it in v1.2.8. It's up on pip now
