### ISSUE TITLE
can't set layout

### ISSUE THREAD

**Issue by marmalodak** [tony/tmuxp#244]
$ tmuxp load -2 ~/.tmuxp/0.yaml
    [Loading] /mnt/myth/john/.tmuxp/0.yaml
    Traceback (most recent call last):
      File "/mnt/myth/john/venvs/util/bin/tmuxp", line 9, in <module>
        load_entry_point('tmuxp==1.2.8', 'console_scripts', 'tmuxp')()
      File "/mnt/myth/john/venvs/util/lib64/python3.5/site-packages/click/core.py", line 722, in __call__
        return self.main(*args, **kwargs)
      File "/mnt/myth/john/venvs/util/lib64/python3.5/site-packages/click/core.py", line 697, in main
        rv = self.invoke(ctx)
      File "/mnt/myth/john/venvs/util/lib64/python3.5/site-packages/click/core.py", line 1066, in invoke
        return _process_result(sub_ctx.command.invoke(sub_ctx))
      File "/mnt/myth/john/venvs/util/lib64/python3.5/site-packages/click/core.py", line 895, in invoke
        return ctx.invoke(self.callback, **ctx.params)
      File "/mnt/myth/john/venvs/util/lib64/python3.5/site-packages/click/core.py", line 535, in invoke
        return callback(*args, **kwargs)
      File "/mnt/myth/john/venvs/util/lib64/python3.5/site-packages/click/decorators.py", line 17, in new_func
        return f(get_current_context(), *args, **kwargs)
      File "/mnt/myth/john/venvs/util/lib64/python3.5/site-packages/tmuxp/cli.py", line 518, in command_load
        load_workspace(config[-1], **tmux_options)
      File "/mnt/myth/john/venvs/util/lib64/python3.5/site-packages/tmuxp/cli.py", line 264, in load_workspace
        builder.build()
      File "/mnt/myth/john/venvs/util/lib64/python3.5/site-packages/tmuxp/workspacebuilder.py", line 178, in build
        for p, pconf in self.iter_create_panes(w, wconf):
      File "/mnt/myth/john/venvs/util/lib64/python3.5/site-packages/tmuxp/workspacebuilder.py", line 292, in iter_create_panes
        w.select_layout(wconf['layout'])
      File "/mnt/myth/john/venvs/util/lib64/python3.5/site-packages/libtmux/window.py", line 126, in select_layout
        raise exc.LibTmuxException(proc.stderr)
    libtmux.exc.LibTmuxException: ["can't set layout: 32a4,729x130,0,0{181x130,0,0,2,182x130,182,0,28,182x130,365,0,17,181x130,548,0,34}"]

    $ tmux select-layout '32a4,729x130,0,0{181x130,0,0,2,182x130,182,0,28,182x130,365,0,17,181x130,548,0,34}'
    $ echo $?
    0

    $ tmuxp -V
    tmuxp 1.2.8

**Comment by tony** [comment]
Can you return your `tmux -V` and your tmuxp config?

**Comment by marmalodak** [comment]
tmux 2.2

and I already deleted the tmuxp config.  So very sorry.

**Comment by tony** [comment]
I need to be able to recreate it on my machine to probe further.

**Comment by marmalodak** [comment]
I agree and I feel dumb for having deleted the config. It was a fatfinger moment.

**Comment by tony** [comment]
It's okay, no problem.  if you are able to recreate this issue and have the config, let me know.

**Comment by sevens-ef** [comment]
I hit this bug today as well and think I figured out the problem (at least in my case): there was a mismatch between the number of panes in the layout (2), and the number of panes in the YAML file (3), resulting in the error.  Commenting out the one of the panes fixed the error.

File to reproduce with:

```yaml
session_name: bug 244
windows:
  - window_name: layout and panes mismatch
    # Layout created using: `split-window -v` (i.e. 2 panes)
    layout: f12f,176x68,0,0[176x34,0,0,45,176x33,0,35,46]
    panes:
      - shell_command:
        - echo pane 1
      - shell_command:
        - echo pane 2
      - shell_command:
        - echo pane 3
```
