### ISSUE TITLE
AssertionError on WSL

### ISSUE THREAD

**Issue by oblitum** [tony/tmuxp#245]
I'm trying tmuxp on WSL (Windows Services for Linux, which is based on Ubuntu 16.04) but loading a session file ends up with:

```
~ ❯❯❯ tmuxp load irc
Traceback (most recent call last):
  File "/home/francisco/.local/bin/tmuxp", line 11, in <module>
    sys.exit(cli.cli())
  File "/home/francisco/.local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/francisco/.local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/francisco/.local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/francisco/.local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/francisco/.local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/francisco/.local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/francisco/.local/lib/python2.7/site-packages/tmuxp/cli.py", line 518, in command_load
    load_workspace(config[-1], **tmux_options)
  File "/home/francisco/.local/lib/python2.7/site-packages/tmuxp/cli.py", line 264, in load_workspace
    builder.build()
  File "/home/francisco/.local/lib/python2.7/site-packages/tmuxp/workspacebuilder.py", line 144, in build
    assert(self.sconf['session_name'] == session.name)
AssertionError
~ ❯❯❯ cat .tmuxp/irc.yaml
session_name: irc
shell_command_before:
  - sleep 0.2
  - tmux set status off
  - cls
windows:
- window_name: weechat
  panes:
  - shell_command:
    - weechat
~ ❯❯❯ tmux -V
tmux 2.1
~ ❯❯❯ python --version
Python 2.7.12
~ ❯❯❯ pip show tmuxp
---
Metadata-Version: 2.0
Name: tmuxp
Version: 1.2.8
Summary: tmux session manager
Home-page: http://github.com/tony/tmuxp/
Author: Tony Narlock
Author-email: tony@git-pull.com
Installer: pip
License: BSD
Location: /home/francisco/.local/lib/python2.7/site-packages
Requires: click, colorama, libtmux, kaptan
Classifiers:
  Development Status :: 5 - Production/Stable
  License :: OSI Approved :: BSD License
  Operating System :: POSIX
  Operating System :: MacOS :: MacOS X
  Environment :: Web Environment
  Intended Audience :: Developers
  Programming Language :: Python
  Programming Language :: Python :: 2.6
  Programming Language :: Python :: 2.7
  Programming Language :: Python :: 3.3
  Programming Language :: Python :: 3.4
  Programming Language :: Python :: 3.5
  Topic :: Utilities
  Topic :: System :: Shells
Entry-points:
  [console_scripts]
  tmuxp = tmuxp:cli.cli
```

For the same session file I have no issues on ArchLinux.

**Comment by tony** [comment]
Any idea if there are CI systems that will allow testing WSL?

**Comment by oblitum** [comment]
No sorry...

**Comment by oblitum** [comment]
From these two prints I've put above the assert:

```python
            print(self.sconf['session_name'])
            print(session.name)
```

I've got these two outputs:

```
irc
prezto
```

irc is the name I give in the session file, prezto is the default session name I get when I start zsh, which automatically launches a tmux session named prezto.

**Comment by oblitum** [comment]
Actually, putting those same two prints just bellow

```python
            else:
                session = self.server.new_session(
                    session_name=self.sconf['session_name']
                )
```

I get the same name sequence. I don't get it, shouldn't it be equal since a `new_session` has been just created with `session_name=self.sconf['session_name']`?

**Comment by oblitum** [comment]
Updating to `2.3~20170504~bzr3827+20-1ubuntu1~ppa0~ubuntu16.04.1` [from this PPA](https://launchpad.net/~pi-rho/+archive/ubuntu/dev) there's no issue anymore.

**Comment by oblitum** [comment]
Updating to tmux `2.3~20170504~bzr3827+20-1ubuntu1~ppa0~ubuntu16.04.1` [from this PPA](https://launchpad.net/~pi-rho/+archive/ubuntu/dev) there's no issue anymore.
