### ISSUE TITLE
yaml.scanner.ScannerError: mapping values are not allowed here

### ISSUE THREAD

**Issue by jungle-boogie** [tony/tmuxp#251]
Hello,

Really eager to try tmuxp out on my TrueOS system, but I'm getting some crash. This looks similar to https://github.com/tony/tmuxp/issues/201, but I can't even get tmuxp to load.

installed via: `pip install --user tmuxp`
My pip uses python3.6

```
Python 3.6.1 (default, Apr 18 2017, 15:40:39) 
[GCC 4.2.1 Compatible Clang 4.0.0 (tags/RELEASE_400/rc4)] on freebsd12
Type "help", "copyright", "credits" or "license" for more information.
>>>
```

```
$ tmuxp load example.yaml 
Traceback (most recent call last):
  File "/usr/home/jungle/bin/tmuxp", line 11, in <module>
    load_entry_point('tmuxp==1.3.0', 'console_scripts', 'tmuxp')()
  File "/usr/local/lib/python3.6/site-packages/click-6.7-py3.6.egg/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click-6.7-py3.6.egg/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click-6.7-py3.6.egg/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click-6.7-py3.6.egg/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click-6.7-py3.6.egg/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click-6.7-py3.6.egg/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/home/jungle/.local/lib/python3.6/site-packages/tmuxp/cli.py", line 520, in command_load
    load_workspace(config[-1], **tmux_options)
  File "/usr/home/jungle/.local/lib/python3.6/site-packages/tmuxp/cli.py", line 225, in load_workspace
    sconfig = sconfig.import_config(config_file).get()
  File "/usr/home/jungle/.local/lib/python3.6/site-packages/kaptan/__init__.py", line 68, in import_config
    self.configuration_data = self.handler.load(value)
  File "/usr/home/jungle/.local/lib/python3.6/site-packages/kaptan/handlers/yaml_handler.py", line 20, in load
    return yaml.load(data)
  File "/usr/home/jungle/.local/lib/python3.6/site-packages/yaml/__init__.py", line 72, in load
    return loader.get_single_data()
  File "/usr/home/jungle/.local/lib/python3.6/site-packages/yaml/constructor.py", line 35, in get_single_data
    node = self.get_single_node()
  File "/usr/home/jungle/.local/lib/python3.6/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/home/jungle/.local/lib/python3.6/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/usr/home/jungle/.local/lib/python3.6/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/home/jungle/.local/lib/python3.6/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/home/jungle/.local/lib/python3.6/site-packages/yaml/composer.py", line 82, in compose_node
    node = self.compose_sequence_node(anchor)
  File "/usr/home/jungle/.local/lib/python3.6/site-packages/yaml/composer.py", line 111, in compose_sequence_node
    node.value.append(self.compose_node(node, index))
  File "/usr/home/jungle/.local/lib/python3.6/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/home/jungle/.local/lib/python3.6/site-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/usr/home/jungle/.local/lib/python3.6/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/home/jungle/.local/lib/python3.6/site-packages/yaml/parser.py", line 428, in parse_block_mapping_key
    if self.check_token(KeyToken):
  File "/usr/home/jungle/.local/lib/python3.6/site-packages/yaml/scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "/usr/home/jungle/.local/lib/python3.6/site-packages/yaml/scanner.py", line 220, in fetch_more_tokens
    return self.fetch_value()
  File "/usr/home/jungle/.local/lib/python3.6/site-packages/yaml/scanner.py", line 576, in fetch_value
    self.get_mark())
yaml.scanner.ScannerError: mapping values are not allowed here
  in "<unicode string>", line 4, column 17:
               panes:
                    ^
```

```
$ cat example.yaml 
session_name: 2-pane-vertical
windows:
        - window_name: my test window
           panes:
             - echo hello
             - echo hello
```

**Comment by jungle-boogie** [comment]
Good news! it was crashing because my yaml file wasn't formatted correctly.

```
$ cat .tmuxp/example.yaml 
session_name: 2-pane-vertical
windows:
  - window_name: my test window
    panes:
      - echo hello
      - echo hello

```

**Comment by apurisrikanth** [comment]
hi  can some one explain me the below error 
[root@node1 playbooks]# ansible-playbook  test.yml
ERROR! Syntax Error while loading YAML.


The error appears to have been in '/etc/ansible/playbooks/test.yml': line 2, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

—--
– name: Install Packages
      ^ here

exception type: <class 'yaml.scanner.ScannerError'>
exception: mapping values are not allowed in this context
  in "<unicode string>", line 2, column 7

**Comment by einarc** [comment]
@srikanth1201  yamllint.com

There's a missing space between - and name

You have
`– name: Install Packages`

It oughta be:
`–  name: Install Packages`

Use the site above or install a linter to validate your code from now on.
Cheers.

**Comment by soloman229** [comment]
can anyone please help for the below error..

The error appears to have been in '/etc/ansible/sample.yml': line 2, column 10, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

----
 - hosts : agent
         ^ here

exception type: <class 'yaml.scanner.ScannerError'>
exception: mapping values are not allowed in this context
  in "<unicode string>", line 2, column 10

**Comment by aqalyani04** [comment]
yaml.scanner.ScannerError
yaml.scanner.ScannerError: mapping values are not allowed here
  in "<unicode string>", line 2, column 13:
      ip_address:
                ^

Traceback (most recent call last)
File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2464, in __call__
return self.wsgi_app(environ, start_response)
File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2450, in wsgi_app
response = self.handle_exception(e)
File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1867, in handle_exception
reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python3.9/dist-packages/flask/_compat.py", line 39, in reraise
raise value
File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2447, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1952, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1821, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python3.9/dist-packages/flask/_compat.py", line 39, in reraise
raise value
File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1950, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1936, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/home/aqalyani/PycharmProjects/quokka/quokka/__init__.py", line 15, in devices
devices = import_devices()
File "/home/aqalyani/PycharmProjects/quokka/quokka/__init__.py", line 9, in import_devices
devices = yaml.safe_load(devices_file.read())
File "/usr/local/lib/python3.9/dist-packages/yaml/__init__.py", line 162, in safe_load
return load(stream, SafeLoader)
File "/usr/local/lib/python3.9/dist-packages/yaml/__init__.py", line 114, in load
return loader.get_single_data()
File "/usr/local/lib/python3.9/dist-packages/yaml/constructor.py", line 49, in get_single_data
node = self.get_single_node()
File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 36, in get_single_node
document = self.compose_document()
File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 55, in compose_document
node = self.compose_node(None, None)
File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 84, in compose_node
node = self.compose_mapping_node(anchor)
File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 127, in compose_mapping_node
while not self.check_event(MappingEndEvent):
File "/usr/local/lib/python3.9/dist-packages/yaml/parser.py", line 98, in check_event
self.current_event = self.state()
File "/usr/local/lib/python3.9/dist-packages/yaml/parser.py", line 428, in parse_block_mapping_key
if self.check_token(KeyToken):
File "/usr/local/lib/python3.9/dist-packages/yaml/scanner.py", line 116, in check_token
self.fetch_more_tokens()
File "/usr/local/lib/python3.9/dist-packages/yaml/scanner.py", line 223, in fetch_more_tokens
return self.fetch_value()
File "/usr/local/lib/python3.9/dist-packages/yaml/scanner.py", line 577, in fetch_value
raise ScannerError(None, None,
yaml.scanner.ScannerError: mapping values are not allowed here
in "<unicode string>", line 2, column 13:
ip_address:
^
The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.
To switch between the interactive traceback and the plaintext one, you can click on the "Traceback" headline. From the text traceback you can also create a paste of it. For code execution mouse-over the frame you want to debug and click on the console icon on the right side.

You can execute arbitrary Python code in the stack frames and there are some extra helpers available for introspection:

dump() shows all variables in the frame
dump(obj) dumps all that's known about the object
Brought to you by DON'T PANIC, your friendly Werkzeug powered traceback interpreter.

**Comment by 78789034166** [comment]
name: CI
on: [push, workflow_dispatch]
jobs:
 build:
 runs-on: windows-latest
 steps:
 - name: Download
 run: Invoke-WebRequest
https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-
stable-windows-amd64.zip -OutFile
ngrok.zip
 - name: Extract
 run: Expand-Archive ngrok.zip
 - name: Auth
 run: .\ngrok\ngrok.exe authtoken
$Env:NGROK_AUTH_TOKEN
 env:
 NGROK_AUTH_TOKEN: ${{
secrets.NGROK_AUTH_TOKEN }}
 - name: Enable TS
