### ISSUE TITLE
no reliable way to detect closed window

### ISSUE THREAD

**Issue by rpodgorny** [tony/tmuxp#88]
...or at least i don't know any. here's what i do and what fails in tmuxp:

w = sess.new_window(attach=False)
w.tmux('respawn-pane', '-k', 'ls -l /')  # or any other short-lived command
if w in sess.list_windows():
  pass

fails with:

Traceback (most recent call last):
  File "/home/radek/scripts/run_all2", line 206, in <module>
    main()
  File "/home/radek/scripts/run_all2", line 192, in main
    print(w)
  File "/usr/lib/python3.4/site-packages/tmuxp/window.py", line 42, in **repr**
    self.get('window_id'),
  File "/usr/lib/python3.4/_collections_abc.py", line 425, in get
    return self[key]
  File "/usr/lib/python3.4/site-packages/tmuxp/util.py", line 134, in __getitem__
    return self._TMUX[key]
  File "/usr/lib/python3.4/site-packages/tmuxp/window.py", line 65, in _TMUX
    return list(filter(by, self.server._windows))[0]
IndexError: list index out of range

...anyway, i'll be happier with being able to do something like w.is_closed() or something.

**Comment by tony** [comment]
(Sorry for the late response.)

This is part of the larger issue of handling concurrency issue between python objects and client-driven interaction.

> i'll be happier with being able to do something like w.is_closed() or something.

I'm thinking the most python thing would be to ``try`` and raise a helpful exception if a server / session / window / pane doesn't exist.  I also equally support am fine with ``is_closed`` and even more complicated introspection to see what changed in the state of the tmux object since last checking.
