### ISSUE TITLE
tmuxp fails to load layout in cygwin

### ISSUE THREAD

**Issue by nfarrar** [tony/tmuxp#99]
I'm attempting to use tmuxp on windows using cygwin. I fired it up and tried to load a layout that loads fine on windows & linux (the layout is actually stored in a project being synchronized via dropbox between computers) ...

```
tmuxp load layout.yaml                                                                                                                                                 
```

This generates the following errors:

```
load /cygdrive/c/Users/nfarrar/Dropbox/Projects/mudfiles/layout.yaml
(I) [14:04:56] tmuxp.cli cli.load_workspace():270 Loading      
/cygdrive/c/Users/nfarrar/Dropbox/Projects/mudfiles/layout.yaml.

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/tmuxp/cli.py", line 271, in load_workspace
    builder.build()
  File "/usr/lib/python2.7/site-packages/tmuxp/workspacebuilder.py", line 149, in build
    for w, wconf in self.iter_create_windows(session):
  File "/usr/lib/python2.7/site-packages/tmuxp/workspacebuilder.py", line 201, in iter_create_windows
    window_index=wconf.get('window_index', ''),
  File "/usr/lib/python2.7/site-packages/tmuxp/session.py", line 181, in new_window
    raise exc.TmuxpException(proc.stderr)
TmuxpException: [u'bad working directory: No such file or directory']

(E) [14:04:00] tmuxp.cli cli.load_workspace():301 [u'bad working directory: No such file or directory']
Error loading workspace. (k)ill, (a)ttach, (d)etach? - (k, a, d) [k]: Session killed.
```

Any suggestions?

**Comment by nfarrar** [comment]
There was an error message to set `export DISABLE_AUTO_TITLE='true' in `~/.zsshrc/`, which seems to have been causing some issues (not exactly sure why), but I did set this.

Then from a tmux session (`testsession`) I was able to run `tmuxp freeze testsession`.
When I attempt to load the session `tmuxp load testsession.yaml` I get the following error:

    tmuxp load testsession.yaml                                                                                                                                                                            ~
    Traceback (most recent call last):
      File "/usr/bin/tmuxp", line 9, in <module>
        load_entry_point('tmuxp==0.1.13', 'console_scripts', 'tmuxp')()
      File "/usr/lib/python2.7/site-packages/tmuxp/cli.py", line 959, in main
        command_load(args)
      File "/usr/lib/python2.7/site-packages/tmuxp/cli.py", line 422, in command_load
        load_workspace(file_user, args)
      File "/usr/lib/python2.7/site-packages/tmuxp/cli.py", line 252, in load_workspace
        sconfig = config.expand(sconfig, os.path.dirname(config_file))
      File "/usr/lib/python2.7/site-packages/tmuxp/config.py", line 223, in expand
        expand(window, parent=sconf) for window in sconf['windows']
      File "/usr/lib/python2.7/site-packages/tmuxp/config.py", line 187, in expand
        sconf['start_directory'] = expandpath(sconf['start_directory'])
      File "/usr/lib/python2.7/site-packages/tmuxp/config.py", line 116, in expandpath
        return os.path.expandvars(os.path.expanduser(_path))
      File "/usr/lib/python2.7/posixpath.py", line 261, in expanduser
        if not path.startswith('~'):
    AttributeError: 'NoneType' object has no attribute 'startswith'

**Comment by tony** [comment]
@nfarrar 
Thanks for the report!

Can you let me know your tmux version, and see your ``testsession.yaml``?

Does your ``.zshrc`` has ``DISABLE_AUTO_TITLE`` set to ``'true'``?

**Comment by tony** [comment]
@nfarrar : I just took a second glance, cygwin!  I never personally tested against cygwin.  Any additional info such as your terminal, os, cygwin version, etc. would he helpful so we can reproduce the issue.
